// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWP99JSDCC1MFAKgeoVAopg9x-PwkSlmw',
    appId: '1:912064990359:web:1c543e753cecab513aedd2',
    messagingSenderId: '912064990359',
    projectId: 'gfb-44',
    authDomain: 'gfb-44.firebaseapp.com',
    storageBucket: 'gfb-44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyvcrdQVeNEdb2-FJpeU5rF78UYRIDQTs',
    appId: '1:912064990359:android:f97b96add5da4a143aedd2',
    messagingSenderId: '912064990359',
    projectId: 'gfb-44',
    storageBucket: 'gfb-44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0CbB69rFHYrd7l_ChPwhb04HQr1GPrS8',
    appId: '1:912064990359:ios:b108d26a2be36d883aedd2',
    messagingSenderId: '912064990359',
    projectId: 'gfb-44',
    storageBucket: 'gfb-44.appspot.com',
    iosBundleId: 'net.codex.fluttersignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0CbB69rFHYrd7l_ChPwhb04HQr1GPrS8',
    appId: '1:912064990359:ios:b108d26a2be36d883aedd2',
    messagingSenderId: '912064990359',
    projectId: 'gfb-44',
    storageBucket: 'gfb-44.appspot.com',
    iosBundleId: 'net.codex.fluttersignin',
  );
}
